[package]
name = "fj-viewer"
version = "0.5.0"
edition = "2021"

description = "The world needs another CAD program."
readme = "../README.md"
repository = "https://github.com/hannobraun/fornjot"
license = "0BSD"
keywords = ["cad", "programmatic", "code-cad"]
categories = ["rendering"]


[dependencies]
bytemuck = "1.9.1"
futures = "0.3.21"
nalgebra = "0.31.0"
parry3d-f64 = "0.8.0"
thiserror = "1.0.31"
tracing = "0.1.34"
wgpu = "0.12.0"
wgpu_glyph = "0.16.0"
winit = "0.26.1"

[dependencies.fj-host]
version = "0.5.0"
path = "../fj-host"

[dependencies.fj-interop]
version = "0.5.0"
path = "../fj-interop"

[dependencies.fj-math]
version = "0.5.0"
path = "../fj-math"

[dependencies.fj-operations]
version = "0.5.0"
path = "../fj-operations"
